const fs = require('fs');

const en = {
  header: {
    jan: "January", janShort: "Jan",
    feb: "February", febShort: "Feb",
    mar: "March", marShort: "Mar",
    apr: "April", aprShort: "Apr",
    may: "May", mayShort: "May",
    jun: "June", junShort: "Jun",
    jul: "July", julShort: "Jul",
    aug: "August", augShort: "Aug",
    sep: "September", sepShort: "Sep",
    oct: "October", octShort: "Oct",
    nov: "November", novShort: "Nov",
    dec: "December", decShort: "Dec",
    save: "Save", cancel: "Cancel", changeName: "Change Mess Name",
    cloudSyncing: "Cloud Backup in progress...",
    cloudSecure: "Backup is secure",
    cloudSaved: "Saved to cloud",
    selectSession: "Select Session Month",
    year26: "2026",
    sessionInfo: "Loading the report for the selected month",
    historyPdf: "3 Months History & PDF"
  },
  members: {
    title: "Members",
    addMember: "Add New Member",
    memberNamePlaceholder: "Member Name (e.g. Jitu, Sagar)",
    btnAdd: "Add Member",
    memberListTitle: "Mess Members List",
    registeredUsers: "Registered Users",
    btnRemove: "Remove"
  },
  bazaar: {
    totalBazaarExpense: "Total Bazaar Expense",
    otherUtilityBills: "Other & Utility Bills",
    addDailyBazaar: "Add Daily Bazaar",
    voiceEntry: "Voice Entry",
    selectDate: "Select Date",
    amount: "Amount (৳)",
    selectBuyer: "Select Buyer (Who spent?)",
    shoppingDetails: "Shopping Details (Optional)",
    shoppingPlaceholder: "e.g., Potato, Dal, Chicken...",
    weeklyDuty: "Weekly Bazaar Duty",
    noDutySet: "No duty set. Set routine from 'More' menu.",
    sharedList: "Shared Bazaar List",
    newItem: "New bazaar item...",
    emptyList: "The list is empty.",
    commonFund: "Common / Mess Fund (No one paid individually)",
    utilityBillsTitle: "Utility & Other Bills (Electricity, Water, etc.)",
    addOtherBill: "Add Other Bill",
    billAmount: "Bill Amount",
    utilityDescPlaceholder: "...Electricity bill, Water bill",
    bazaarRecords: "Bazaar Expense Records"
  },
  meals: {
    mealCalcLabel: "Meal Calculation",
    mealCalcDesc: "Set the total meals or custom limit for your mess instead of the configured meals for individual or daily changes. This system is designed for simple and easy calculation.",
    totalMealsOrAvg: "Total Meals (Total or Daily Avg)",
    totalMealsCount: "Total Meals Count",
    activeCount: "active",
    setFixedMealsBtn: "Set Fixed Meals",
    membersMealOverview: "Members Meal Overview",
    mealCountLabel: "Meal Count:",
    mealCount: "Meal Count:",
    mealRecord: "Meal Record",
    individualMeals: "Meals"
  },
  deposits: {
    totalDepositsTitle: "Total Deposits",
    membersTotal: "Members Total Deposit",
    addMemberFirst: "Add a member first to update deposits.",
    balanceDueTitle: "Balance Empty! Payment due",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    confirmNewDeposit: "Confirm New Deposit",
    depositEntryFor: "DEPOSIT ENTRY FOR?",
    depositDate: "DEPOSIT DATE",
    btnDeposit: "Deposit",
    depositRecords: "Deposit Records",
    noDepositRecords: "No deposit transactions yet",
    amountPlaceholder: "Enter amount...",
    selectMember: "Select Member",
    sync1: "All transaction data is automatically saved and real-time synced to your Firebase Cloud Database."
  },
  sideMenu: {
    menuTitle: "Menu",
    backToMenu: "Back to Menu",
    ledgerTitle: "Final Calculation",
    dutyTitle: "Mess Duty & Roles",
    finalLedgerBtn: "Final Ledger",
    finalLedgerDesc: "Real-time mess calculator & refund dashboard",
    dutiesBtn: "Mess Duty Schedule",
    dutiesDesc: "Routine for responsibilities (Bazaar, Meal Manager, Cleaner)",
    daysAssigned: "Days Assigned",
    newSession: "New Session",
    newSessionDesc: "Reset calculations and start a new session",
    oldSessions: "Old Sessions",
    oldSessionsDesc: "Restore previous session data",
    pdfExport: "PDF Export",
    pdfExportDesc: "Download final calculation and expense statement for all members",
    superAdmin: "Super Admin Panel",
    superAdminDesc: "View all users and mess data, and download PDFs",
    changePassword: "Change Password",
    logout: "Log Out",
    resetAll: "Reset all mess data",
    changeLang: "Change Language",
    langTitle: "Select Language",
    langBn: "🇧🇩 বাংলা (Bangladesh)",
    langEn: "🇺🇸 English (USA/Global)",
    langAr: "🇸🇦 العربية (Saudi Arabia)",
    langHi: "🇮🇳 हिन्दी (India)",
    memberList: "Members List",
    newSessionWarning: "Warning: Starting a new session will reset all expenses to zero. This action cannot be undone.",
    passwordPrompt: "Enter your password",
    confirm: "Confirm",
    oldSessionsList: "Previous Sessions",
    exportReport: "Export Report",
    cancel: "Cancel"
  },
  nav: {
    members: "Members",
    expenses: "Expenses",
    meals: "Meals",
    deposits: "Deposits",
    bazaar: "Bazaar"
  }
};

const bn = {
  header: {
    jan: "জানুয়ারি", janShort: "জানু",
    feb: "ফেব্রুয়ারি", febShort: "ফেব",
    mar: "মার্চ", marShort: "মার্চ",
    apr: "এপ্রিল", aprShort: "এপ্রি",
    may: "মে", mayShort: "মে",
    jun: "জুন", junShort: "জুন",
    jul: "জুলাই", julShort: "জুল",
    aug: "আগস্ট", augShort: "আগ",
    sep: "সেপ্টেম্বর", sepShort: "সেপ্টে",
    oct: "অক্টোবর", octShort: "অক্টো",
    nov: "নভেম্বর", novShort: "নভে",
    dec: "ডিসেম্বর", decShort: "ডিসে",
    save: "সেভ", cancel: "বাতিল", changeName: "মেসের নাম পরিবর্তন",
    cloudSyncing: "ক্লাউড ব্যাকআপ হচ্ছে...",
    cloudSecure: "ব্যাকআপ নিরাপদ",
    cloudSaved: "ক্লাউডে সেভ হয়েছে",
    selectSession: "সেশন মাস নির্বাচন করুন",
    year26: "২০২৬",
    sessionInfo: "নির্বাচিত মাসের রিপোর্ট লোড হচ্ছে",
    historyPdf: "৩ মাসের হিস্ট্রি ও পিডিএফ"
  },
  members: {
    title: "সদস্য",
    addMember: "নতুন সদস্য যোগ করুন",
    memberNamePlaceholder: "সদস্যের নাম (যেমন: জিতু, সাগর)",
    btnAdd: "সদস্য যোগ করুন",
    memberListTitle: "মেস সদস্য তালিকা",
    registeredUsers: "নিবন্ধিত ব্যবহারকারী",
    btnRemove: "বাদ দিন"
  },
  bazaar: {
    totalBazaarExpense: "মোট বাজার খরচ",
    otherUtilityBills: "অন্যান্য এবং ইউটিলিটি বিল",
    addDailyBazaar: "দৈনিক বাজার যোগ করুন",
    voiceEntry: "ভয়েস এন্ট্রি",
    selectDate: "তারিখ নির্বাচন",
    amount: "পরিমাণ (৳)",
    selectBuyer: "ক্রেতা নির্বাচন করুন (কে খরচ করেছে?)",
    shoppingDetails: "বাজারের বিবরণ (ঐচ্ছিক)",
    shoppingPlaceholder: "যেমন: আলু, ডাল, মুরগি...",
    weeklyDuty: "সাপ্তাহিক বাজার ডিউটি",
    noDutySet: "কোন ডিউটি সেট করা নেই। 'More' মেনু থেকে রুটিন সেট করুন।",
    sharedList: "শেয়ার্ড বাজার তালিকা",
    newItem: "নতুন বাজার আইটেম...",
    emptyList: "তালিকাটি খালি।",
    commonFund: "কমন / মেস ফান্ড (ব্যক্তিগতভাবে কেউ দেয়নি)",
    utilityBillsTitle: "ইউটিলিটি ও অন্যান্য বিল (বিদ্যুৎ, পানি ইত্যাদি)",
    addOtherBill: "অন্যান্য বিল যোগ করুন",
    billAmount: "বিলের পরিমাণ",
    utilityDescPlaceholder: "...বিদ্যুৎ বিল, পানি বিল",
    bazaarRecords: "বাজার খরচের রেকর্ডস"
  },
  meals: {
    mealCalcLabel: "মিল হিসাব",
    mealCalcDesc: "ব্যক্তিগত বা দৈনিক মিল কম-বেশি পরিবর্তনের জন্য নির্ধারিত মিলের জায়গায় আপনার মেসের মোট মিল বা কাস্টম লিমিট সেট করে নিন। এই সিস্টেমটি সহজ ও সরল গণনার জন্য ডিজাইন করা হয়েছে।",
    totalMealsOrAvg: "মোট মিল (সর্বমোট বা দৈনিক গড়)",
    totalMealsCount: "মোট মিল সংখ্যা",
    activeCount: "সক্রিয়",
    setFixedMealsBtn: "ফিক্সড মিল সেট করুন",
    membersMealOverview: "সদস্যদের মিল ওভারভিউ",
    mealCountLabel: "মিল হিসাব:",
    mealCount: "মিল সংখ্যা:",
    mealRecord: "মিল রেকর্ড",
    individualMeals: "টি"
  },
  deposits: {
    totalDepositsTitle: "সর্বমোট জমা",
    membersTotal: "সদস্যদের সর্বমোট জমা",
    addMemberFirst: "মেসে জমা আপডেট করার জন্য প্রথমে সদস্য যোগ করুন।",
    balanceDueTitle: "জমা টাকা শেষ! ব্যালেন্স বকেয়া",
    save: "সেভ",
    cancel: "বাতিল",
    edit: "এডিট",
    confirmNewDeposit: "নতুন জমা নিশ্চিত করুন",
    depositEntryFor: "কার জন্য জমা?",
    depositDate: "জমার তারিখ",
    btnDeposit: "জমা করুন",
    depositRecords: "জমার রেকর্ডসমূহ",
    noDepositRecords: "এখনো কোনো জমার রেকর্ড নেই",
    amountPlaceholder: "হিসাব দিন...",
    selectMember: "সদস্য নির্বাচন করুন",
    sync1: "সকল ট্রানজেকশন ডেটা আপনার ফায়ারবেস ক্লাউড ডাটাবেজে স্বয়ংক্রিয়ভাবে সেভ ও রিয়েল-টাইম সিঙ্ক হচ্ছে।"
  },
  sideMenu: {
    menuTitle: "মেনু",
    backToMenu: "মূল মেনু ফিরে যান",
    ledgerTitle: "চূড়ান্ত হিসাব",
    dutyTitle: "মেস ডিউটি ও দায়িত্ব",
    finalLedgerBtn: "হিসাব (Final Ledger)",
    finalLedgerDesc: "রিয়েল-টাইম মেস ক্যালকুলেটর ও রিফান্ড ড্যাশবোর্ড",
    dutiesBtn: "মেস ডিউটি রুটিন (Mess Duty Schedule)",
    dutiesDesc: "কার কোন দিন কি দায়িত্ব (বাজার, মিল ম্যানেজার, ক্লিনার) তার রুটিন",
    daysAssigned: "দিন অ্যাসাইনড",
    newSession: "নতুন সেশন শুরু",
    newSessionDesc: "হিসাব রিসেট করে নতুন সেশন শুরু করুন",
    oldSessions: "পুরনো সেশন",
    oldSessionsDesc: "পূর্ববর্তী সেশনের ডাটা পুনরুদ্ধার করুন",
    pdfExport: "পিডিএফ হিসাব এক্সপোর্ট",
    pdfExportDesc: "মেস বাজার খরচ ও সকল সদস্যদের চূড়ান্ত হিসাব বিবরণী ডাউনলোড করুন",
    superAdmin: "সুপার অ্যাডমিন প্যানেল",
    superAdminDesc: "সকল ইউজার ও মেসের ডাটা দেখুন এবং পিডিএফ ডাউনলোড করুন",
    changePassword: "পাসওয়ার্ড পরিবর্তন",
    logout: "লগ আউট",
    resetAll: "সকল মেস ডাটা রিসেট করুন",
    changeLang: "ভাষা পরিবর্তন",
    langTitle: "ভাষা নির্বাচন করুন (Select Language)",
    langBn: "🇧🇩 বাংলা (Bangladesh)",
    langEn: "🇺🇸 English (USA/Global)",
    langAr: "🇸🇦 العربية (Saudi Arabia)",
    langHi: "🇮🇳 हिन्दी (India)",
    memberList: "সদস্য তালিকা",
    newSessionWarning: "সতর্কতা: নতুন সেশন শুরু করলে সকল খরচের হিসাব জিরো হয়ে যাবে। এই প্রক্রিয়াটি পূর্বাবস্থায় ফেরানো সম্ভব নয়।",
    passwordPrompt: "আপনার পাসওয়ার্ড দিন",
    confirm: "নিশ্চিত করুন",
    oldSessionsList: "পূর্ববর্তী সেশন সমূহ",
    exportReport: "রিপোর্ট এক্সপোর্ট করুন",
    cancel: "বাতিল করুন"
  },
  nav: {
    members: "সদস্য",
    expenses: "খরচ",
    meals: "ভোজন",
    deposits: "জমা",
    bazaar: "বাজার"
  }
};

const ar = {
  header: {
    jan: "يناير", janShort: "يناير",
    feb: "فبراير", febShort: "فبراير",
    mar: "مارس", marShort: "مارس",
    apr: "أبريل", aprShort: "أبريل",
    may: "مايو", mayShort: "مايو",
    jun: "يونيو", junShort: "يونيو",
    jul: "يوليو", julShort: "يوليو",
    aug: "أغسطس", augShort: "أغسطس",
    sep: "سبتمبر", sepShort: "سبتمبر",
    oct: "أكتوبر", octShort: "أكتوبر",
    nov: "نوفمبر", novShort: "نوفمبر",
    dec: "ديسمبر", decShort: "ديسمبر",
    save: "حفظ", cancel: "إلغاء", changeName: "تغيير اسم الفوضى",
    cloudSyncing: "النسخ الاحتياطي السحابي قيد التقدم...",
    cloudSecure: "النسخ الاحتياطي آمن",
    cloudSaved: "تم الحفظ في السحابة",
    selectSession: "حدد شهر الجلسة",
    year26: "2026",
    sessionInfo: "يتم تحميل التقرير للشهر المحدد",
    historyPdf: "تاريخ 3 أشهر و PDF"
  },
  members: {
    title: "الأعضاء",
    addMember: "إضافة عضو جديد",
    memberNamePlaceholder: "اسم العضو (مثل: جيتو، ساجار)",
    btnAdd: "إضافة عضو",
    memberListTitle: "قائمة أعضاء الفوضى",
    registeredUsers: "المستخدمون المسجلون",
    btnRemove: "إزالة"
  },
  bazaar: {
    totalBazaarExpense: "إجمالي مصاريف السوق",
    otherUtilityBills: "فواتير المرافق الأخرى",
    addDailyBazaar: "إضافة سوق يومي",
    voiceEntry: "إدخال صوتي",
    selectDate: "تحديد التاريخ",
    amount: "المبلغ (৳)",
    selectBuyer: "تحديد المشتري (من أنفق؟)",
    shoppingDetails: "تفاصيل التسوق (اختياري)",
    shoppingPlaceholder: "مثال: بطاطس، عدس، دجاج...",
    weeklyDuty: "واجب السوق الأسبوعي",
    noDutySet: "لم يتم تعيين واجب. قم بتعيين الروتين من قائمة 'المزيد'.",
    sharedList: "قائمة السوق المشتركة",
    newItem: "عنصر سوق جديد...",
    emptyList: "القائمة فارغة.",
    commonFund: "صندوق مشترك / فوضى (لم يدفع أحد بشكل فردي)",
    utilityBillsTitle: "فواتير المرافق وغيرها (الكهرباء والماء، إلخ.)",
    addOtherBill: "إضافة فاتورة أخرى",
    billAmount: "مبلغ الفاتورة",
    utilityDescPlaceholder: "...فاتورة الكهرباء، فاتورة الماء",
    bazaarRecords: "سجلات مصاريف السوق"
  },
  meals: {
    mealCalcLabel: "حساب الوجبة",
    mealCalcDesc: "قم بتعيين إجمالي الوجبات أو الحد المخصص للفوضى بدلاً من الوجبات المحددة للتغييرات الفردية أو اليومية. تم تصميم هذا النظام للحساب البسيط.",
    totalMealsOrAvg: "إجمالي الوجبات (الإجمالي أو المتوسط اليومي)",
    totalMealsCount: "إجمالي عدد الوجبات",
    activeCount: "نشط",
    setFixedMealsBtn: "تعيين وجبات ثابتة",
    membersMealOverview: "نظرة عامة على وجبات الأعضاء",
    mealCountLabel: "عدد الوجبات:",
    mealCount: "عدد الوجبات:",
    mealRecord: "سجل الوجبات",
    individualMeals: "وجبات"
  },
  deposits: {
    totalDepositsTitle: "إجمالي الودائع",
    membersTotal: "إجمالي ودائع الأعضاء",
    addMemberFirst: "أضف عضوًا أولاً لتحديث الودائع.",
    balanceDueTitle: "الرصيد فارغ! الدفع مستحق",
    save: "حفظ",
    cancel: "إلغاء",
    edit: "تعديل",
    confirmNewDeposit: "تأكيد الإيداع الجديد",
    depositEntryFor: "إيداع من أجل؟",
    depositDate: "تاريخ الإيداع",
    btnDeposit: "إيداع",
    depositRecords: "سجلات الإيداع",
    noDepositRecords: "لا توجد معاملات إيداع حتى الآن",
    amountPlaceholder: "أدخل المبلغ...",
    selectMember: "حدد العضو",
    sync1: "يتم حفظ جميع بيانات المعاملات تلقائيًا ومزامنتها في الوقت الفعلي مع قاعدة بيانات Firebase الخاصة بك."
  },
  sideMenu: {
    menuTitle: "القائمة",
    backToMenu: "العودة للقائمة",
    ledgerTitle: "الحساب النهائي",
    dutyTitle: "الواجبات والأدوار",
    finalLedgerBtn: "دفتر الأستاذ النهائي",
    finalLedgerDesc: "آلة حاسبة للفوضى في الوقت الفعلي ولوحة معلومات استرداد الأموال",
    dutiesBtn: "جدول واجبات الفوضى",
    dutiesDesc: "روتين المسؤوليات (السوق، مدير الوجبات، المنظف)",
    daysAssigned: "أيام معينة",
    newSession: "جلسة جديدة",
    newSessionDesc: "إعادة تعيين الحسابات وبدء جلسة جديدة",
    oldSessions: "الجلسات القديمة",
    oldSessionsDesc: "استعادة بيانات الجلسة السابقة",
    pdfExport: "تصدير PDF",
    pdfExportDesc: "قم بتنزيل الحساب النهائي وبيان المصروفات لجميع الأعضاء",
    superAdmin: "لوحة تحكم المشرف",
    superAdminDesc: "عرض جميع المستخدمين وبيانات الفوضى، وتنزيل ملفات PDF",
    changePassword: "تغيير كلمة المرور",
    logout: "تسجيل الخروج",
    resetAll: "إعادة تعيين جميع بيانات الفوضى",
    changeLang: "تغيير اللغة",
    langTitle: "اختر اللغة",
    langBn: "🇧🇩 البنغالية (Bangladesh)",
    langEn: "🇺🇸 الإنجليزية (USA/Global)",
    langAr: "🇸🇦 العربية (Saudi Arabia)",
    langHi: "🇮🇳 الهندية (India)",
    memberList: "قائمة الأعضاء",
    newSessionWarning: "تحذير: سيؤدي بدء جلسة جديدة إلى إعادة تعيين جميع النفقات إلى الصفر. لا يمكن التراجع عن هذا الإجراء.",
    passwordPrompt: "أدخل كلمة المرور الخاصة بك",
    confirm: "تأكيد",
    oldSessionsList: "الجلسات السابقة",
    exportReport: "تصدير التقرير",
    cancel: "إلغاء"
  },
  nav: {
    members: "الأعضاء",
    expenses: "النفقات",
    meals: "الوجبات",
    deposits: "الودائع",
    bazaar: "السوق"
  }
};

const hi = {
  header: {
    jan: "जनवरी", janShort: "जन",
    feb: "फ़रवरी", febShort: "फ़र",
    mar: "मार्च", marShort: "मार्च",
    apr: "अप्रैल", aprShort: "अप्रै",
    may: "मई", mayShort: "मई",
    jun: "जून", junShort: "जून",
    jul: "जुलाई", julShort: "जुल",
    aug: "अगस्त", augShort: "अग",
    sep: "सितंबर", sepShort: "सितं",
    oct: "अक्टूबर", octShort: "अक्टू",
    nov: "नवंबर", novShort: "नवं",
    dec: "दिसंबर", decShort: "दिसं",
    save: "सहेजें", cancel: "रद्द करें", changeName: "मेस का नाम बदलें",
    cloudSyncing: "क्लाउड बैकअप हो रहा है...",
    cloudSecure: "बैकअप सुरक्षित है",
    cloudSaved: "क्लाउड में सहेजा गया",
    selectSession: "सत्र का महीना चुनें",
    year26: "2026",
    sessionInfo: "चयनित महीने के लिए रिपोर्ट लोड हो रही है",
    historyPdf: "3 महीने का इतिहास और पीडीएफ"
  },
  members: {
    title: "सदस्य",
    addMember: "नया सदस्य जोड़ें",
    memberNamePlaceholder: "सदस्य का नाम (जैसे: जितु, सागर)",
    btnAdd: "सदस्य जोड़ें",
    memberListTitle: "मेस सदस्य सूची",
    registeredUsers: "पंजीकृत उपयोगकर्ता",
    btnRemove: "हटाएं"
  },
  bazaar: {
    totalBazaarExpense: "कुल बाज़ार खर्च",
    otherUtilityBills: "अन्य और उपयोगिता बिल",
    addDailyBazaar: "दैनिक बाज़ार जोड़ें",
    voiceEntry: "वॉयस एंट्री",
    selectDate: "तारीख चुनें",
    amount: "रकम (৳)",
    selectBuyer: "खरीदार चुनें (किसने खर्च किया?)",
    shoppingDetails: "खरीदारी विवरण (वैकल्पिक)",
    shoppingPlaceholder: "जैसे, आलू, दाल, चिकन...",
    weeklyDuty: "साप्ताहिक बाज़ार ड्यूटी",
    noDutySet: "कोई ड्यूटी सेट नहीं है। 'More' मेनू से रूटीन सेट करें।",
    sharedList: "साझा बाज़ार सूची",
    newItem: "नया बाज़ार आइटम...",
    emptyList: "सूची खाली है।",
    commonFund: "सामान्य / मेस फंड (किसी ने व्यक्तिगत रूप से भुगतान नहीं किया)",
    utilityBillsTitle: "उपयोगिता और अन्य बिल (बिजली, पानी, आदि)",
    addOtherBill: "अन्य बिल जोड़ें",
    billAmount: "बिल राशि",
    utilityDescPlaceholder: "...बिजली बिल, पानी बिल",
    bazaarRecords: "बाज़ार खर्च रिकॉर्ड"
  },
  meals: {
    mealCalcLabel: "भोजन गणना",
    mealCalcDesc: "व्यक्तिगत या दैनिक परिवर्तनों के लिए कॉन्फ़िगर किए गए भोजन के बजाय अपने मेस के लिए कुल भोजन या कस्टम सीमा निर्धारित करें। यह प्रणाली सरल और आसान गणना के लिए डिज़ाइन की गई है।",
    totalMealsOrAvg: "भोजन संख्या (कुल या दैनिक औसत)",
    totalMealsCount: "कुल भोजन संख्या",
    activeCount: "सक्रिय",
    setFixedMealsBtn: "भोजन निर्धारित करें",
    membersMealOverview: "सदस्यों का भोजन अवलोकन",
    mealCountLabel: "भोजन गणना:",
    mealCount: "भोजन गणना:",
    mealRecord: "भोजन रिकॉर्ड",
    individualMeals: "भोजन"
  },
  deposits: {
    totalDepositsTitle: "कुल जमा",
    membersTotal: "सदस्यों की कुल जमा राशि",
    addMemberFirst: "जमा अपडेट करने के लिए पहले एक सदस्य जोड़ें।",
    balanceDueTitle: "बैलेंस खाली! भुगतान देय",
    save: "सहेजें",
    cancel: "रद्द करें",
    edit: "संपादित करें",
    confirmNewDeposit: "नए डिपॉजिट की पुष्टि करें",
    depositEntryFor: "किसके लिए डिपॉजिट?",
    depositDate: "डिपॉजिट की तारीख",
    btnDeposit: "डिपॉजिट करें",
    depositRecords: "डिपॉजिट रिकॉर्ड",
    noDepositRecords: "अभी तक कोई डिपॉजिट लेनदेन नहीं हुआ है",
    amountPlaceholder: "रकम दर्ज करें...",
    selectMember: "सदस्य चुनें",
    sync1: "सभी लेन-देन डेटा स्वचालित रूप से सहेजा जाता है और आपके फायरबेस क्लाउड डेटाबेस में वास्तविक समय में सिंक होता है।"
  },
  sideMenu: {
    menuTitle: "मेनू",
    backToMenu: "मेनू पर वापस जाएं",
    ledgerTitle: "अंतिम गणना",
    dutyTitle: "मेस ड्यूटी और भूमिकाएं",
    finalLedgerBtn: "अंतिम खाता (Final Ledger)",
    finalLedgerDesc: "रीयल-टाइम मेस कैलकुलेटर और रिफंड डैशबोर्ड",
    dutiesBtn: "मेस ड्यूटी शेड्यूल",
    dutiesDesc: "जिम्मेदारियों की दिनचर्या (बाज़ार, भोजन प्रबंधक, क्लीनर)",
    daysAssigned: "दिन सौंपे गए",
    newSession: "नया सत्र",
    newSessionDesc: "गणना रीसेट करें और नया सत्र शुरू करें",
    oldSessions: "पुराने सत्र",
    oldSessionsDesc: "पिछले सत्र का डेटा पुनर्स्थापित करें",
    pdfExport: "पीडीएफ निर्यात",
    pdfExportDesc: "सभी सदस्यों के लिए अंतिम गणना और व्यय विवरण डाउनलोड करें",
    superAdmin: "सुपर एडमिन पैनल",
    superAdminDesc: "सभी उपयोगकर्ताओं और मेस डेटा देखें, और पीडीएफ डाउनलोड करें",
    changePassword: "पासवर्ड बदलें",
    logout: "लॉग आउट",
    resetAll: "सभी मेस डेटा रीसेट करें",
    changeLang: "भाषा बदलें",
    langTitle: "भाषा चुनें",
    langBn: "🇧🇩 बंगाली (Bangladesh)",
    langEn: "🇺🇸 अंग्रेजी (USA/Global)",
    langAr: "🇸🇦 अरबी (Saudi Arabia)",
    langHi: "🇮🇳 हिन्दी (India)",
    memberList: "सदस्यों की सूची",
    newSessionWarning: "चेतावनी: एक नया सत्र शुरू करने से सभी खर्च शून्य हो जाएंगे। इस कार्रवाई को पूर्ववत नहीं किया जा सकता है।",
    passwordPrompt: "अपना पासवर्ड डालें",
    confirm: "पुष्टि करें",
    oldSessionsList: "पिछले सत्र",
    exportReport: "रिपोर्ट निर्यात करें",
    cancel: "रद्द करें"
  },
  nav: {
    members: "सदस्य",
    expenses: "खर्च",
    meals: "भोजन",
    deposits: "जमा",
    bazaar: "बाज़ार"
  }
};

const finalTranslations = { en, bn, ar, hi };

// Only overwrite existing keys, don't remove other keys like 'passwordModal' which are in existing translations
let oldCode = fs.readFileSync('src/i18n/translations.ts', 'utf8');
const objStr = oldCode.replace(/export type LanguageType = 'en' \| 'bn' \| 'ar' \| 'hi';\n\nexport const translations: Record<LanguageType, any> = /, '').replace(/;\n$/, '');
const oldTrans = JSON.parse(objStr);

function deepMerge(target, source) {
  for (const key in source) {
    if (source[key] instanceof Object && key in target) {
      Object.assign(source[key], deepMerge(target[key], source[key]));
    }
  }
  Object.assign(target || {}, source);
  return target;
}

for (const lang of ['en', 'bn', 'ar', 'hi']) {
    oldTrans[lang] = deepMerge(oldTrans[lang] || {}, finalTranslations[lang]);
}

const newCode = `export type LanguageType = 'en' | 'bn' | 'ar' | 'hi';\n\nexport const translations: Record<LanguageType, any> = ${JSON.stringify(oldTrans, null, 2)};\n`;
fs.writeFileSync('src/i18n/translations.ts', newCode);
